[functions]
  node_bundler = "esbuild"
  external_node_modules = ["onnxruntime-node"]
  included_files = [
    "node_modules/onnxruntime-node/**",
    "public/models/**",
    "data/features/iot/**"
  ]
[functions."api/iot/h3/daily"]
  memory = 1024
  timeout = 25
[functions."warm-forecaster"]
  schedule = "*/4 * * * *"  