[functions]
  node_bundler = "esbuild"
  external_node_modules = ["onnxruntime-node"]
  included_files = [
    "node_modules/onnxruntime-node/**",
    "public/models/**",
    "data/features/iot/**"
  ]
